[helpers]

[default]
depends = []

[default.files]
dunst = "~/.config/dunst"
hypr = "~/.config/hypr"
i3 = "~/.config/i3"
i3blocks = "~/.config/i3blocks"
i3status = "~/.config/i3status"
kanshi = "~/.config/kanshi"
nvim = "~/.config/nvim"
rofi = "~/.config/rofi"
waybar = {target = "~/.config/waybar", type = "symbolic"}
wallpapers = {target = "~/Pictures/Wallpapers", type = "symbolic"}
kitty = "~/.config/kitty"
"starship.toml" = "~/.config/starship.toml"
eww = {target = "~/.config/eww", type = "symbolic"}

[default.variables]

[settings]
default_target_type = "automatic"
